### ISSUE TITLE
Defining style

### ISSUE THREAD

**Issue by DannyBen** [makandra/query_diet#11]
Is there a way to define a different style to the widget, other than trying to `important!`-override the CSS selectors?

**Comment by codener** [comment]
The only way I can think of is to include your custom styles into the body right *after* rendering the query diet widget. This should override the standard query_diet styles.

Ah, you could also try to increase selector specificity inside your normal stylesheets by writing your custom styles like this: `body > #query_diet_widget` (I’m at home and cannot try it myself right now). HTH!

**Comment by DannyBen** [comment]
Understood, thanks.

**Comment by codener** [comment]
Let me know whether you got it working!

**Comment by DannyBen** [comment]
Yeah, got it working easily, just by adding `!important` to any CSS property I wish to overwrite. This way it doesn't matter that the stylesheet is linked before the inline style.

Added this to my SCSS pipeline:

```css
div#query_diet {
	display: inline-block !important;
	font-size: 20px !important;
	padding: 10px !important;
	top: initial !important;
	right: initial !important;
	bottom: 0; 
	left: 0;
}
```
